# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{callsite}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joshua Hull"]
  s.date = %q{2010-05-20}
  s.description = %q{Caller/backtrace parser with some useful utilities for manipulating the load path, and doing other relative things.}
  s.email = %q{joshbuddy@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/callsite.rb",
    "lib/dirge.rb",
    "lib/load_path_find.rb",
    "lib/loaders/kernel_dir.rb",
    "lib/loaders/kernel_require.rb",
    "lib/loaders/load_path.rb"
  ]
  s.homepage = %q{http://github.com/joshbuddy/callsite}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Caller/backtrace parser with some useful utilities for manipulating the load path, and doing other relative things.}
  s.test_files = [
    "spec/data/dir1/test.rb",
    "spec/data/dir1/test2.rb",
    "spec/data/dir2/test.rb",
    "spec/data/dir2/test2.rb",
    "spec/dirge_spec.rb",
    "spec/load_path_find_spec.rb",
    "spec/test:2test/test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

